alias ls='ls --color=auto --group-directories-first -F'
alias ll='ls -lh --color=auto --group-directories-first -F'
alias la='ls -lha --color=auto --group-directories-first -F'
alias df='df -h --output=source,fstype,size,used,avail,pcent,target -x tmpfs -x devtmpfs -x fuse.portal'
alias ytmp3='yt-dlp -x --audio-format mp3'
alias ytaudio='yt-dlp -x'
alias ytsubs='yt-dlp --write-sub --sub-lang "en.*"'
alias iplookup='curl https://icanhazip.com'
alias genpasswd='openssl rand 60 | openssl base64 -A'
alias mpv-powersave='mpv --vd-lavc-fast=yes --vd-lavc-skiploopfilter=nonkey'
